### ISSUE TITLE
Random Images Not Working

### ISSUE THREAD

**Issue by SH20RAJ** [imagecdn/random-image-service#131]
Like this :- ![Uploading Screenshot 2024-07-07 at 10.13.47 AM.png…]()

**Comment by SH20RAJ** [comment]
<img width="1470" alt="Screenshot 2024-07-07 at 10 13 47 AM" src="https://github.com/imagecdn/random-image-service/assets/66713844/87333f29-6322-4dd7-b850-d01e31ba22d2">

**Comment by SH20RAJ** [comment]
> Thanks for raising this @SH20RAJ, this outage should now be resolved.
> 
> Unsplash deprecated the API this relied on last year and recently shut it off. I've now added two new providers: [Lorem Flickr](https://loremflickr.com/) and [Lorem Picsum](https://picsum.photos/) and so the API is returning responses again.
> 
> Note: In future I may deprecate this service in favour of one of them.


I want to ask that do you have any plans to depreciate imagecdn.app , because I'm using it....

**Comment by alexwilson** [comment]
Currently no plans, and it has enough usage that I definitely can't/won't just switch it off!
